// This file is automatically generated. Do not modify it manually.
export const firebaseConfig = {
  apiKey: "AIzaSy...",
  authDomain: "friendly-chat-60991.firebaseapp.com",
  projectId: "friendly-chat-60991",
  storageBucket: "friendly-chat-60991.appspot.com",
  messagingSenderId: "832962208433",
  appId: "1:832962208433:web:961448655b35398ab775c7",
  measurementId: "G-9L2R2V8H18"
};
